# Generated by Django 5.1.8 on 2025-04-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
