# Generated by Django 5.1.8 on 2025-04-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='slug',
        ),
    ]
